name: C++ Fibonacci Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile the program
      run: g++ test_fibonacci.cpp -o test_fibonacci

    - name: Run tests
      run: ./test_fibonacci
