name: C++ Fibonacci Test

on:
  push:
    branches: [ main ]  # Cambia 'main' si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++

    - name: Compile the program
      run: g++ tests/test_fibonacci.cpp src/fibonacci.cpp -o test_fibonacci

    - name: Run the test
      run: ./test_fibonacci
